#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.
set -u # Treat unset variables as an error.

# Determine if usage of FileBot beta is enabled.
if is-bool-val-true "${USE_FILEBOT_BETA:-0}"; then
    echo "/config/beta"
else
    echo "/opt/filebot"
fi

# vim:ft=sh:ts=4:sw=4:et:sts=4
