#!/bin/sh

# force JVM language and encoding settings
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# force GTK look and feel
export GNOME_DESKTOP_SESSION_ID=this-is-deprecated

FILEBOT_HOME="${FILEBOT_HOME:-/opt/filebot}"
APP_DATA=/config

# choose archive extractor / media characteristics parser
ARCHIVE_EXTRACTOR="ShellExecutables"
MEDIA_PARSER="libmediainfo"

LIBRARY_PATH="/usr/lib"

# options for this container
# NOTE: Use a file dialog that doesn't require JavaFX.
# See:
#   https://www.filebot.net/forums/viewtopic.php?p=53552#p53552
#   https://www.filebot.net/forums/viewtopic.php?t=3913
CONTAINER_OPTS=" \
    -DuseGVFS=false \
    -Dapplication.update=skip \
    -Dawt.useSystemAAFontSettings=on \
    -Dnet.filebot.UserFiles.fileChooser=Zenity \
"

# start filebot
exec /usr/lib/jvm/default-jvm/bin/java \
    -Dapplication.deployment=docker \
    -Dnet.filebot.license="$APP_DATA/license.psm" \
    -Dnet.filebot.media.parser="$MEDIA_PARSER" \
    -Dnet.filebot.archive.extractor="$ARCHIVE_EXTRACTOR" \
    --add-opens=java.base/java.lang=ALL-UNNAMED \
    --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
    --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
    --add-opens=java.base/java.util=ALL-UNNAMED \
    --add-opens=java.base/java.util.function=ALL-UNNAMED \
    --add-opens=java.base/java.util.regex=ALL-UNNAMED \
    --add-opens=java.base/java.net=ALL-UNNAMED \
    --add-opens=java.base/java.io=ALL-UNNAMED \
    --add-opens=java.base/java.nio=ALL-UNNAMED \
    --add-opens=java.base/java.nio.file=ALL-UNNAMED \
    --add-opens=java.base/java.nio.file.attribute=ALL-UNNAMED \
    --add-opens=java.base/java.nio.channels=ALL-UNNAMED \
    --add-opens=java.base/java.nio.charset=ALL-UNNAMED \
    --add-opens=java.base/java.time=ALL-UNNAMED \
    --add-opens=java.base/java.time.chrono=ALL-UNNAMED \
    --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
    --add-opens=java.base/java.text=ALL-UNNAMED \
    --add-opens=java.base/sun.nio.fs=ALL-UNNAMED \
    --add-opens=java.logging/java.util.logging=ALL-UNNAMED \
    --add-opens=java.desktop/java.awt=ALL-UNNAMED \
    --add-opens=java.desktop/sun.awt=ALL-UNNAMED \
    --add-opens=java.desktop/sun.swing=ALL-UNNAMED \
    --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED \
    --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED \
    -XX:+DisableAttachMechanism \
    -Dunixfs=false \
    -DuseExtendedFileAttributes=true \
    -DuseCreationDate=false \
    -Djava.net.useSystemProxies=false \
    -Djna.nosys=false \
    -Djna.nounpack=true \
    -Djna.boot.library.path="$LIBRARY_PATH" \
    -Djna.library.path="$LIBRARY_PATH" \
    -Djava.library.path="$LIBRARY_PATH" \
    -Dapplication.dir="$APP_DATA" \
    -Dapplication.cache="$APP_DATA/cache" \
    -Djava.io.tmpdir="$APP_DATA/tmp" \
    -Dfile.encoding="UTF-8" \
    -Dsun.jnu.encoding="UTF-8" \
    -Duser.home="$APP_DATA" \
    -Djava.util.prefs.PreferencesFactory=net.filebot.util.prefs.FilePreferencesFactory \
    -Dnet.filebot.util.prefs.file="$APP_DATA/prefs.properties" \
    -client \
    $JAVA_OPTS $FILEBOT_OPTS $CONTAINER_OPTS -jar "$FILEBOT_HOME/jar/filebot.jar" "$@"
